// In this file you can specify the trial data for your experiment
    
const trial_info = {
    key_press_practice: [
    {
        question: "Are these two figures the same except for their orientation?",
        picture: "images/13_50_different.jpg",
        picture_nr: 13,
        rotation: 50,
        key1: 'f',
        key2: 'j',
        f: 'same',
        j: 'different',
        expected: 'different'
    },
    {
        question: "Are these two figures the same except for their orientation?",
        picture: 'images/13_50_same.jpg',
        picture_nr: 13,
        rotation: 50,
        key1: 'f',
        key2: 'j',
        f: 'same',
        j: 'different',
        expected: 'same'
    },
    {
        question: "Are these two figures the same except for their orientation?",
        picture: 'images/13_150_different.jpg',
        picture_nr: 13,
        rotation: 150,
        key1: 'f',
        key2: 'j',
        f: 'same',
        j: 'different',
        expected: 'different'
    },
    {
        question: "Are these two figures the same except for their orientation?",
        picture: 'images/13_150_same.jpg',
        picture_nr: 13,
        rotation: 150,
        key1: 'f',
        key2: 'j',
        f: 'same',
        j: 'different',
        expected: 'same'
    },
    {
        question: "Are these two figures the same except for their orientation?",
        picture: 'images/14_50_different.jpg',
        picture_nr: 14,
        rotation: 50,
        key1: 'f',
        key2: 'j',
        f: 'same',
        j: 'different',
        expected: 'different'
    },
    {
        question: "Are these two figures the same except for their orientation?",
        picture: 'images/14_50_same.jpg',
        picture_nr: 14,
        rotation: 50,
        key1: 'f',
        key2: 'j',
        f: 'same',
        j: 'different',
        expected: 'same'
    },
    {
        question: "Are these two figures the same except for their orientation?",
        picture: 'images/14_150_different.jpg',
        picture_nr: 14,
        rotation: 150,
        key1: 'f',
        key2: 'j',
        f: 'same',
        j: 'different',
        expected: 'different'
    },
    {
        question: "Are these two figures the same except for their orientation?",
        picture: 'images/14_150_same.jpg',
        picture_nr: 14,
        rotation: 150,
        key1: 'f',
        key2: 'j',
        f: 'same',
        j: 'different',
        expected: 'same'
    },
    {
        question: "Are these two figures the same except for their orientation?",
        picture: 'images/15_50_different.jpg',
        picture_nr: 15,
        rotation: 50,
        key1: 'f',
        key2: 'j',
        f: 'same',
        j: 'different',
        expected: 'different'
    },
    {
        question: "Are these two figures the same except for their orientation?",
        picture: 'images/15_50_same.jpg',
        picture_nr: 15,
        rotation: 50,
        key1: 'f',
        key2: 'j',
        f: 'same',
        j: 'different',
        expected: 'same'
    },
    {
        question: "Are these two figures the same except for their orientation?",
        picture: 'images/15_150_different.jpg',
        picture_nr: 15,
        rotation: 150,
        key1: 'f',
        key2: 'j',
        f: 'same',
        j: 'different',
        expected: 'different'
    },
    {
        question: "Are these two figures the same except for their orientation?",
        picture: 'images/15_150_same.jpg',
        picture_nr: 15,
        rotation: 150,
        key1: 'f',
        key2: 'j',
        f: 'same',
        j: 'different',
        expected: 'same'
    },
],
 key_press_main: [
        {
        question: "Are these two figures the same except for their orientation?",
        picture: "images/1_50_different.jpg",
        picture_nr: 1,
        rotation: 50,
        key1: 'f',
        key2: 'j',
        f: 'same',
        j: 'different',
        expected: 'different'
    },
    {
        question: "Are these two figures the same except for their orientation?",
        picture: 'images/1_50_same.jpg',
        picture_nr: 1,
        rotation: 50,
        key1: 'f',
        key2: 'j',
        f: 'same',
        j: 'different',
        expected: 'same'
    },
    {
        question: "Are these two figures the same except for their orientation?",
        picture: 'images/1_150_different.jpg',
        picture_nr: 1,
        rotation: 150,
        key1: 'f',
        key2: 'j',
        f: 'same',
        j: 'different',
        expected: 'different'
    },
    {
        question: "Are these two figures the same except for their orientation?",
        picture: 'images/1_150_same.jpg',
        picture_nr: 1,
        rotation: 150,
        key1: 'f',
        key2: 'j',
        f: 'same',
        j: 'different',
        expected: 'same'
    },
    {
        question: "Are these two figures the same except for their orientation?",
        picture: 'images/2_50_different.jpg',
        picture_nr: 2,
        rotation: 50,
        key1: 'f',
        key2: 'j',
        f: 'same',
        j: 'different',
        expected: 'different'
    },
    {
        question: "Are these two figures the same except for their orientation?",
        picture: 'images/2_50_same.jpg',
        picture_nr: 2,
        rotation: 50,
        key1: 'f',
        key2: 'j',
        f: 'same',
        j: 'different',
        expected: 'same'
    },
    {
        question: "Are these two figures the same except for their orientation?",
        picture: 'images/2_150_different.jpg',
        picture_nr: 2,
        rotation: 150,
        key1: 'f',
        key2: 'j',
        f: 'same',
        j: 'different',
        expected: 'different'
    },
    {
        question: "Are these two figures the same except for their orientation?",
        picture: 'images/2_150_same.jpg',
        picture_nr: 2,
        rotation: 150,
        key1: 'f',
        key2: 'j',
        f: 'same',
        j: 'different',
        expected: 'same'
    },
    {
        question: "Are these two figures the same except for their orientation?",
        picture: 'images/3_50_different.jpg',
        picture_nr: 3,
        rotation: 50,
        key1: 'f',
        key2: 'j',
        f: 'same',
        j: 'different',
        expected: 'different'
    },
    {
        question: "Are these two figures the same except for their orientation?",
        picture: 'images/3_50_same.jpg',
        picture_nr: 3,
        rotation: 50,
        key1: 'f',
        key2: 'j',
        f: 'same',
        j: 'different',
        expected: 'same'
    },
    {
        question: "Are these two figures the same except for their orientation?",
        picture: 'images/3_150_different.jpg',
        picture_nr: 3,
        rotation: 150,
        key1: 'f',
        key2: 'j',
        f: 'same',
        j: 'different',
        expected: 'different'
    },
    {
        question: "Are these two figures the same except for their orientation?",
        picture: 'images/3_150_same.jpg',
        picture_nr: 3,
        rotation: 150,
        key1: 'f',
        key2: 'j',
        f: 'same',
        j: 'different',
        expected: 'same'
    },
        {
        question: "Are these two figures the same except for their orientation?",
        picture: "images/4_50_different.jpg",
        picture_nr: 4,
        rotation: 50,
        key1: 'f',
        key2: 'j',
        f: 'same',
        j: 'different',
        expected: 'different'
    },
    {
        question: "Are these two figures the same except for their orientation?",
        picture: 'images/4_50_same.jpg',
        picture_nr: 4,
        rotation: 50,
        key1: 'f',
        key2: 'j',
        f: 'same',
        j: 'different',
        expected: 'same'
    },
    {
        question: "Are these two figures the same except for their orientation?",
        picture: 'images/4_150_different.jpg',
        picture_nr: 4,
        rotation: 150,
        key1: 'f',
        key2: 'j',
        f: 'same',
        j: 'different',
        expected: 'different'
    },
    {
        question: "Are these two figures the same except for their orientation?",
        picture: 'images/4_150_same.jpg',
        picture_nr: 4,
        rotation: 150,
        key1: 'f',
        key2: 'j',
        f: 'same',
        j: 'different',
        expected: 'same'
    },
    {
        question: "Are these two figures the same except for their orientation?",
        picture: 'images/5_50_different.jpg',
        picture_nr: 5,
        rotation: 50,
        key1: 'f',
        key2: 'j',
        f: 'same',
        j: 'different',
        expected: 'different'
    },
    {
        question: "Are these two figures the same except for their orientation?",
        picture: 'images/5_50_same.jpg',
        picture_nr: 5,
        rotation: 50,
        key1: 'f',
        key2: 'j',
        f: 'same',
        j: 'different',
        expected: 'same'
    },
    {
        question: "Are these two figures the same except for their orientation?",
        picture: 'images/5_150_different.jpg',
        picture_nr: 5,
        rotation: 150,
        key1: 'f',
        key2: 'j',
        f: 'same',
        j: 'different',
        expected: 'different'
    },
    {
        question: "Are these two figures the same except for their orientation?",
        picture: 'images/5_150_same.jpg',
        picture_nr: 5,
        rotation: 150,
        key1: 'f',
        key2: 'j',
        f: 'same',
        j: 'different',
        expected: 'same'
    },
    {
        question: "Are these two figures the same except for their orientation?",
        picture: 'images/6_50_different.jpg',
        picture_nr: 6,
        rotation: 50,
        key1: 'f',
        key2: 'j',
        f: 'same',
        j: 'different',
        expected: 'different'
    },
    {
        question: "Are these two figures the same except for their orientation?",
        picture: 'images/6_50_same.jpg',
        picture_nr: 6,
        rotation: 50,
        key1: 'f',
        key2: 'j',
        f: 'same',
        j: 'different',
        expected: 'same'
    },
    {
        question: "Are these two figures the same except for their orientation?",
        picture: 'images/6_150_different.jpg',
        picture_nr: 6,
        rotation: 150,
        key1: 'f',
        key2: 'j',
        f: 'same',
        j: 'different',
        expected: 'different'
    },
    {
        question: "Are these two figures the same except for their orientation?",
        picture: 'images/6_150_same.jpg',
        picture_nr: 6,
        rotation: 150,
        key1: 'f',
        key2: 'j',
        f: 'same',
        j: 'different',
        expected: 'same'
    },
        {
        question: "Are these two figures the same except for their orientation?",
        picture: "images/7_50_different.jpg",
        picture_nr: 7,
        rotation: 50,
        key1: 'f',
        key2: 'j',
        f: 'same',
        j: 'different',
        expected: 'different'
    },
    {
        question: "Are these two figures the same except for their orientation?",
        picture: 'images/7_50_same.jpg',
        picture_nr: 7,
        rotation: 50,
        key1: 'f',
        key2: 'j',
        f: 'same',
        j: 'different',
        expected: 'same'
    },
    {
        question: "Are these two figures the same except for their orientation?",
        picture: 'images/7_150_different.jpg',
        picture_nr: 7,
        rotation: 150,
        key1: 'f',
        key2: 'j',
        f: 'same',
        j: 'different',
        expected: 'different'
    },
    {
        question: "Are these two figures the same except for their orientation?",
        picture: 'images/7_150_same.jpg',
        picture_nr: 7,
        rotation: 150,
        key1: 'f',
        key2: 'j',
        f: 'same',
        j: 'different',
        expected: 'same'
    },
    {
        question: "Are these two figures the same except for their orientation?",
        picture: 'images/8_50_different.jpg',
        picture_nr: 8,
        rotation: 50,
        key1: 'f',
        key2: 'j',
        f: 'same',
        j: 'different',
        expected: 'different'
    },
    {
        question: "Are these two figures the same except for their orientation?",
        picture: 'images/8_50_same.jpg',
        picture_nr: 8,
        rotation: 50,
        key1: 'f',
        key2: 'j',
        f: 'same',
        j: 'different',
        expected: 'same'
    },
    {
        question: "Are these two figures the same except for their orientation?",
        picture: 'images/8_150_different.jpg',
        picture_nr: 8,
        rotation: 150,
        key1: 'f',
        key2: 'j',
        f: 'same',
        j: 'different',
        expected: 'different'
    },
    {
        question: "Are these two figures the same except for their orientation?",
        picture: 'images/8_150_same.jpg',
        picture_nr: 8,
        rotation: 150,
        key1: 'f',
        key2: 'j',
        f: 'same',
        j: 'different',
        expected: 'same'
    },
    {
        question: "Are these two figures the same except for their orientation?",
        picture: 'images/9_50_different.jpg',
        picture_nr: 9,
        rotation: 50,
        key1: 'f',
        key2: 'j',
        f: 'same',
        j: 'different',
        expected: 'different'
    },
    {
        question: "Are these two figures the same except for their orientation?",
        picture: 'images/9_50_same.jpg',
        picture_nr: 9,
        rotation: 50,
        key1: 'f',
        key2: 'j',
        f: 'same',
        j: 'different',
        expected: 'same'
    },
    {
        question: "Are these two figures the same except for their orientation?",
        picture: 'images/9_150_different.jpg',
        picture_nr: 9,
        rotation: 150,
        key1: 'f',
        key2: 'j',
        f: 'same',
        j: 'different',
        expected: 'different'
    },
    {
        question: "Are these two figures the same except for their orientation?",
        picture: 'images/9_150_same.jpg',
        picture_nr: 9,
        rotation: 150,
        key1: 'f',
        key2: 'j',
        f: 'same',
        j: 'different',
        expected: 'same'
    },
        {
        question: "Are these two figures the same except for their orientation?",
        picture: "images/10_50_different.jpg",
        picture_nr: 10,
        rotation: 50,
        key1: 'f',
        key2: 'j',
        f: 'same',
        j: 'different',
        expected: 'different'
    },
    {
        question: "Are these two figures the same except for their orientation?",
        picture: 'images/10_50_same.jpg',
        picture_nr: 10,
        rotation: 50,
        key1: 'f',
        key2: 'j',
        f: 'same',
        j: 'different',
        expected: 'same'
    },
    {
        question: "Are these two figures the same except for their orientation?",
        picture: 'images/10_150_different.jpg',
        picture_nr: 10,
        rotation: 150,
        key1: 'f',
        key2: 'j',
        f: 'same',
        j: 'different',
        expected: 'different'
    },
    {
        question: "Are these two figures the same except for their orientation?",
        picture: 'images/10_150_same.jpg',
        picture_nr: 10,
        rotation: 150,
        key1: 'f',
        key2: 'j',
        f: 'same',
        j: 'different',
        expected: 'same'
    },
    {
        question: "Are these two figures the same except for their orientation?",
        picture: 'images/11_50_different.jpg',
        picture_nr: 11,
        rotation: 50,
        key1: 'f',
        key2: 'j',
        f: 'same',
        j: 'different',
        expected: 'different'
    },
    {
        question: "Are these two figures the same except for their orientation?",
        picture: 'images/11_50_same.jpg',
        picture_nr: 11,
        rotation: 50,
        key1: 'f',
        key2: 'j',
        f: 'same',
        j: 'different',
        expected: 'same'
    },
    {
        question: "Are these two figures the same except for their orientation?",
        picture: 'images/11_150_different.jpg',
        picture_nr: 11,
        rotation: 150,
        key1: 'f',
        key2: 'j',
        f: 'same',
        j: 'different',
        expected: 'different'
    },
    {
        question: "Are these two figures the same except for their orientation?",
        picture: 'images/11_150_same.jpg',
        picture_nr: 11,
        rotation: 150,
        key1: 'f',
        key2: 'j',
        f: 'same',
        j: 'different',
        expected: 'same'
    },
    {
        question: "Are these two figures the same except for their orientation?",
        picture: 'images/12_50_different.jpg',
        picture_nr: 12,
        rotation: 50,
        key1: 'f',
        key2: 'j',
        f: 'same',
        j: 'different',
        expected: 'different'
    },
    {
        question: "Are these two figures the same except for their orientation?",
        picture: 'images/12_50_same.jpg',
        picture_nr: 12,
        rotation: 50,
        key1: 'f',
        key2: 'j',
        f: 'same',
        j: 'different',
        expected: 'same'
    },
    {
        question: "Are these two figures the same except for their orientation?",
        picture: 'images/12_150_different.jpg',
        picture_nr: 12,
        rotation: 150,
        key1: 'f',
        key2: 'j',
        f: 'same',
        j: 'different',
        expected: 'different'
    },
    {
        question: "Are these two figures the same except for their orientation?",
        picture: 'images/12_150_same.jpg',
        picture_nr: 12,
        rotation: 150,
        key1: 'f',
        key2: 'j',
        f: 'same',
        j: 'different',
        expected: 'same'
    },
]
};
